name: CI
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Build on JDK ${{ matrix.Java }
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK ${{ matrix.Java }
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }
          cache: 'gradle'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Compile
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: assemble spotlessCheck
      - name: QA
        uses: burrunan/gradle-cache-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: build sonarqube
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Test Results
          files: '**/build/test-results/**/*.xml'
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
